apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-google-safebrowsing
  namespace: kube-system
  labels:
    app: kube-google-safebrowsing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-google-safebrowsing
  template:
    metadata:
      labels:
        app: kube-google-safebrowsing
    spec:
      serviceAccountName: kube-google-safebrowsing
      containers:
      - name: kube-google-safebrowsing
        image: ghcr.io/airfocusio/kube-google-safebrowsing:0.1.0-rc.3
        ports:
        - containerPort: 1024
          name: metrics
        env:
        - name: GOOGLE_SAFEBROWSING_API_KEY
          valueFrom:
            secretKeyRef:
              name: kube-google-safebrowsing
              key: google-safebrowsing-api-key
