apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-google-safebrowsing
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-google-safebrowsing
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-google-safebrowsing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-google-safebrowsing
subjects:
- kind: ServiceAccount
  name: kube-google-safebrowsing
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-google-safebrowsing
  name: kube-google-safebrowsing
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 1024
    protocol: TCP
    targetPort: metrics
  selector:
    app: kube-google-safebrowsing
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-google-safebrowsing
  name: kube-google-safebrowsing
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-google-safebrowsing
  template:
    metadata:
      labels:
        app: kube-google-safebrowsing
    spec:
      containers:
      - image: ghcr.io/airfocusio/kube-google-safebrowsing:latest
        name: kube-google-safebrowsing
        ports:
        - containerPort: 1024
          name: metrics
      serviceAccountName: kube-google-safebrowsing
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-google-safebrowsing
  name: kube-google-safebrowsing
  namespace: kube-system
spec:
  groups:
  - name: kube-google-safebrowsing
    rules: []
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-google-safebrowsing
  name: kube-google-safebrowsing
  namespace: kube-system
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: kube-google-safebrowsing
