apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-google-safebrowsing
  namespace: kube-system
  labels:
    app: kube-google-safebrowsing
spec:
  groups:
  - name: kube-google-safebrowsing
    rules:
    - alert: GoogleSafebrowsingThreatForDomain
      annotations:
        description: A threat for domain {{ $labels.domain }} has been found on Google safebrowsing. Visit https://search.google.com/search-console for more details.
        summary: Google safebrowsing threat for {{ $labels.domain }}.
      expr: max by (domain) (google_safebrowsing_threat_matches) > 0
      labels:
        severity: critical
