apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-google-safebrowsing
  namespace: kube-system
  labels:
    app: kube-google-safebrowsing
spec:
  selector:
    matchLabels:
      app: kube-google-safebrowsing
  endpoints:
    - port: metrics
