apiVersion: v1
kind: Service
metadata:
  name: kube-google-safebrowsing
  namespace: kube-system
  labels:
    app: kube-google-safebrowsing
spec:
  type: ClusterIP
  selector:
    app: kube-google-safebrowsing
  ports:
    - name: metrics
      protocol: TCP
      port: 1024
      targetPort: metrics
