name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Install kind
      run: |
        mkdir -p $HOME/bin
        curl -Lo $HOME/bin/kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
        chmod +x $HOME/bin/kind
        echo "$HOME/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: |
        ./test/cluster/start.sh
        go test -v -timeout 60m ./...
      env:
        GOOGLE_SAFEBROWSING_API_KEY: ${{ secrets.GOOGLE_SAFEBROWSING_API_KEY }}
